services:
  - type: web
    name: zone-drop-multiplayer
    env: node
    rootDir: zone-drop
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
